version: "3.7"

services:
  # ggia-postgres:
  #   container_name: "ggia-db-dev"
  #   image: docker.io/bitnami/postgresql:11
  #   volumes:
  #     - 'postgresql_data:/bitnami/postgresql'
  #   environment:
  #     - POSTGRESQL_PASSWORD=postgres
  #     - POSTGRESQL_USER=postgres
  #     - POSTGRESQL_DATABASE=ggia-backend
  #   restart: always

  ggia-backend:
    container_name: "ggia-backend-dev"
    build:
      context: .
    ports:
      - "8001:8000"
    # depends_on:
    #   - ggia-postgres
    restart: on-failure

# volumes:
#   postgresql_data:
#     driver: local
      
