"""initial migration

Revision ID: 4dcc08f4c3e1
Revises: 
Create Date: 2022-01-06 13:51:00.584702

"""
from alembic import op
from ggia_app import fetch_data
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dcc08f4c3e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    countries = op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    transport_modes = op.create_table('transport_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('passenger_km_per_person', sa.Float(), nullable=True),
    sa.Column('average_occupancy', sa.Float(), nullable=True),
    sa.Column('emission_factor_per_km', sa.Float(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Seed data added by Mir Jalal
    op.bulk_insert(countries, fetch_data.fetch_countries("CSVfiles/Transport_simplified dataset CSV.csv"))
    op.bulk_insert(transport_modes, fetch_data.fetch_transport_modes("CSVfiles/Transport_simplified dataset CSV.csv"))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transport_modes')
    op.drop_table('countries')
    # ### end Alembic commands ###
