"""adding yearly growth factors

Revision ID: a56bba9775d0
Revises: ce5d154ac327
Create Date: 2022-01-21 12:37:02.673176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from ggia_app import fetch_data

revision = 'a56bba9775d0'
down_revision = 'ce5d154ac327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    yearly_growth_factors = op.create_table('yearly_growth_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('growth_factor_name', sa.String(), nullable=True),
    sa.Column('growth_factor_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yearly_growth_factors')
    # ### end Alembic commands ###
